export const CHAOSIUM_SKILL_BASES: Record<string, number> = {
  Brawl: 25,
  Dodge: 0,
  'Fighting (Axe)': 15,
  'Fighting (Chainsaw)': 10,
  'Fighting (Flail)': 10,
  'Fighting (Garrote)': 15,
  'Fighting (Spear)': 20,
  'Fighting (Sword)': 20,
  'Fighting (Whip)': 5,
  Throw: 20,
  Handgun: 20,
  'Rifle/Shotgun': 25,
  'Firearms (Bow)': 15,
  'Firearms (Flamethrower)': 10,
  'Firearms (Heavy Weapons)': 10,
  'Firearms (Machine Gun)': 10,
  'Firearms (Submachine Gun)': 15,
  Charm: 15,
  'Fast Talk': 5,
  Intimidate: 15,
  Persuade: 10,
  Disguise: 5,
  Psychology: 10,
  'Credit Rating': 0,
  Archaeology: 1,
  History: 5,
  'Library Use': 20,
  'Spot Hidden': 25,
  Track: 10,
  Listen: 20,
  'Read Lips': 1,
  Accounting: 5,
  Anthropology: 1,
  Appraise: 5,
  'Language (Latin)': 1,
  'Language (Ancient Greek)': 1,
  'Language (Own)': 0,
  'Natural World': 10,
  Occult: 5,
  'Science (Geology)': 1,
  'Science (Astronomy)': 1,
  'Science (Biology)': 1,
  'Science (Botany)': 1,
  'Science (Chemistry)': 1,
  'Science (Cryptography)': 1,
  'Science (Engineering)': 1,
  'Science (Mathematics)': 10,
  'Science (Meteorology)': 1,
  'Science (Pharmacy)': 1,
  'Science (Physics)': 1,
  'Science (Zoology)': 1,
  'Computer Use': 5,
  Electronics: 10,
  Law: 5,
  Medicine: 1,
  Hypnosis: 1,
  'Cthulhu Mythos': 0,
  'Drive Auto': 20,
  'Mechanical Repair': 10,
  'Operate Heavy Machinery': 1,
  'Electrical Repair': 10,
  Locksmith: 1,
  'Pilot (Aircraft)': 1,
  'Pilot (Boat)': 1,
  Ride: 5,
  Survival: 10,
  Climb: 20,
  Diving: 1,
  Jump: 20,
  Swim: 20,
  'Sleight of Hand': 10,
  Stealth: 20,
  'First Aid': 30,
  'Art/Craft (Acting)': 5,
  'Art/Craft (Cobbler)': 5,
  'Art/Craft (Barber)': 5,
  'Art/Craft (Cook)': 5,
  'Art/Craft (Dancer)': 5,
  'Art/Craft (Fine Art)': 5,
  'Art/Craft (Forgery)': 5,
  'Art/Craft (Morris Dancer)': 5,
  'Art/Craft (Opera Singer)': 5,
  'Art/Craft (Painter & Decorator)': 5,
  'Art/Craft (Photographer)': 5,
  'Art/Craft (Potter)': 5,
  'Art/Craft (Sculptor)': 5,
  'Art/Craft (Writer)': 5,
};


